[package]
name = "mdns-app"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.26"
libp2p = { version = "0.51.2", features = ["async-std","tcp", "dns", "gossipsub","mdns","websocket","noise","mplex","yamux"] }
async-std = { version = "1.12.0" , features = ["attributes"]}